import {createHmac,timingSafeEqual} from "node:crypto";
import {z} from "zod";

export const whatsappEventSchema=z.object({event_id:z.string().min(1).max(200),event_type:z.enum(["message","delivery"]),sender_id:z.string().min(3).max(100),provider_message_id:z.string().min(1).max(200),timestamp:z.string().datetime(),message:z.object({type:z.enum(["text","option"]),text:z.string().max(2000).optional(),option_id:z.string().max(100).optional()}).optional(),delivery:z.object({status:z.enum(["accepted","sent","delivered","read","failed"])}).optional()});
export type WhatsAppEvent=z.infer<typeof whatsappEventSchema>;

const metaWebhookSchema=z.object({object:z.literal("whatsapp_business_account"),entry:z.array(z.object({id:z.string(),changes:z.array(z.object({field:z.literal("messages"),value:z.object({messages:z.array(z.object({from:z.string(),id:z.string(),timestamp:z.string(),type:z.string(),text:z.object({body:z.string()}).optional(),interactive:z.object({type:z.string(),button_reply:z.object({id:z.string(),title:z.string()}).optional(),list_reply:z.object({id:z.string(),title:z.string()}).optional()}).optional(),button:z.object({payload:z.string(),text:z.string()}).optional()})).optional(),statuses:z.array(z.object({id:z.string(),status:z.enum(["sent","delivered","read","failed"]),timestamp:z.string(),recipient_id:z.string()})).optional()})}))}))});

export function validWebhookSignature(raw:string,signature:string|null,secret:string){if(!signature)return false;const expected=createHmac("sha256",secret).update(raw).digest("hex");const supplied=signature.replace(/^sha256=/,"");return supplied.length===expected.length&&timingSafeEqual(Buffer.from(supplied),Buffer.from(expected))}

export function normalizeMetaWebhook(payload:unknown):WhatsAppEvent[]{const parsed=metaWebhookSchema.safeParse(payload);if(!parsed.success)return [];const events:WhatsAppEvent[]=[];for(const entry of parsed.data.entry)for(const change of entry.changes){for(const message of change.value.messages??[]){const reply=message.interactive?.button_reply??message.interactive?.list_reply;const optionId=reply?.id??message.button?.payload;const text=message.text?.body??reply?.title??message.button?.text;if(!text&&!optionId)continue;events.push({event_id:`message:${message.id}`,event_type:"message",sender_id:message.from,provider_message_id:message.id,timestamp:new Date(Number(message.timestamp)*1000).toISOString(),message:optionId?{type:"option",option_id:optionId,text}:{type:"text",text}})}for(const status of change.value.statuses??[])events.push({event_id:`status:${status.id}:${status.status}:${status.timestamp}`,event_type:"delivery",sender_id:status.recipient_id,provider_message_id:status.id,timestamp:new Date(Number(status.timestamp)*1000).toISOString(),delivery:{status:status.status}})}return events}

export async function sendWhatsAppText(to:string,body:string){const token=process.env.WHATSAPP_ACCESS_TOKEN,phoneNumberId=process.env.WHATSAPP_PHONE_NUMBER_ID,version=process.env.WHATSAPP_GRAPH_API_VERSION;if(!token||!phoneNumberId||!version)return {ok:false as const,error:"provider_not_configured"};const response=await fetch(`https://graph.facebook.com/${version}/${phoneNumberId}/messages`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({messaging_product:"whatsapp",recipient_type:"individual",to,type:"text",text:{preview_url:false,body}})});const result=await response.json().catch(()=>null) as {messages?:Array<{id:string}>,error?:{message?:string}}|null;if(!response.ok)return {ok:false as const,error:result?.error?.message??"send_failed"};return {ok:true as const,messageId:result?.messages?.[0]?.id??null}}

export const mainMenu={node:"main_menu",text:"Welcome to Tebelopele. Choose an option:",options:[{id:"services",label:"Services"},{id:"facilities",label:"Facilities and hours"},{id:"appointments",label:"Appointments"},{id:"health_information",label:"Health information"},{id:"profile",label:"My profile and preferences",requires_verification:true},{id:"privacy",label:"Privacy and consent"},{id:"helplines",label:"Helplines"},{id:"human",label:"Talk to a person"}]};
export function resolveMenu(option?:string){if(!option||["menu","start","0"].includes(option.toLowerCase()))return mainMenu;const item=mainMenu.options.find(o=>o.id===option);if(!item)return {...mainMenu,text:"I did not recognise that choice. Please choose from the main menu."};if(item.requires_verification)return {node:"identity_required",text:"For your privacy, profile information requires identity verification. Please use the secure web portal or ask a staff member for help.",options:[{id:"main_menu",label:"Main menu"}]};if(option==="human")return {node:"human_handoff",text:"I will place this conversation in the human support queue. Automated replies will pause when an agent takes over.",options:[{id:"main_menu",label:"Main menu"}]};return {node:option,text:`You selected ${item.label}. Approved ${item.label.toLowerCase()} information will be presented here.`,options:[{id:"main_menu",label:"Main menu"}]}}
