import { updateClientProfile } from "@/app/client/actions";
import { getClientContext } from "@/lib/client-data";

type Props = { searchParams: Promise<{ saved?: string; error?: string }> };

export default async function ProfilePage({ searchParams }: Props) {
  const [client, params] = await Promise.all([getClientContext(), searchParams]);
  return <div className="portal-page form-page"><div className="portal-heading"><div><p className="welcome-line">Personal information</p><h1>My profile</h1><p>Keep the basic details used in your Tebelopele service journey up to date.</p></div></div>{params.saved && <div className="alert alert--success" role="status">Your profile was saved.</div>}{params.error && <div className="alert alert--error" role="alert">{params.error === "validation" ? "Check the highlighted information and try again." : params.error === "setup" ? "Supabase must be connected before information can be saved." : "Your profile could not be saved. Try again."}</div>}<form action={updateClientProfile} className="settings-form"><fieldset disabled={!client.configured}><legend>Profile details</legend><div className="field-grid"><label>Full display name<input name="display_name" defaultValue={client.displayName} required maxLength={120}/></label><label>Preferred name <span>Optional</span><input name="preferred_name" defaultValue={client.preferredName} maxLength={120}/></label><label>Email address<input value={client.email} readOnly aria-describedby="email-help"/><small id="email-help">Your sign-in email is managed through your secure account.</small></label><label>Mobile number <span>Optional</span><input name="phone" type="tel" defaultValue={client.phone} maxLength={30} autoComplete="tel"/></label><label>Date of birth <span>Optional</span><input name="date_of_birth" type="date" defaultValue={client.dateOfBirth} max={new Date().toISOString().slice(0,10)}/></label></div><div className="form-actions"><button className="button button--primary" type="submit">Save profile</button></div></fieldset></form></div>;
}
