import Link from "next/link"; import { CalendarDays,MapPin,Plus } from "lucide-react";
import { getAppointments,getOpenSlots } from "@/lib/appointment-data"; import { cancelAppointment,rescheduleAppointment } from "@/app/client/appointment-actions";
export default async function AppointmentsPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const [{configured,items},{items:slots},params]=await Promise.all([getAppointments(),getOpenSlots(),searchParams]);
 return <div className="portal-page"><div className="portal-heading"><div><p className="welcome-line">Care schedule</p><h1>My appointments</h1><p>Book, review or cancel your visits.</p></div><Link className="button button--primary" href="/client/appointments/new"><Plus size={18}/>Book</Link></div>
 {!configured&&<div className="preview-notice"><strong>Preview data</strong><span>These appointments are fictional and cannot be changed.</span></div>}
 {params.booked&&<p className="alert alert--success">Appointment confirmed.</p>}{params.cancelled&&<p className="alert alert--success">Appointment cancelled.</p>}{params.rescheduled&&<p className="alert alert--success">Appointment rescheduled.</p>}{params.error&&<p className="alert alert--error">That appointment change could not be completed.</p>}
 <div className="record-list">{items.map(a=><article key={a.id}><div className="record-date"><strong>{new Intl.DateTimeFormat("en-BW",{day:"2-digit",month:"short"}).format(new Date(a.starts_at))}</strong><span>{new Intl.DateTimeFormat("en-BW",{hour:"2-digit",minute:"2-digit"}).format(new Date(a.starts_at))}</span></div><div><span className={`state state--${a.status}`}>{a.status}</span><h2>{a.service?.name}</h2><p><MapPin size={15}/>{a.facility?.name}</p>{a.visit_reason&&<small>{a.visit_reason}</small>}</div>{configured&&["confirmed","requested"].includes(a.status)&&<div className="appointment-actions">{slots.some(s=>s.service?.id===a.service?.id)&&<form action={rescheduleAppointment}><input type="hidden" name="appointment_id" value={a.id}/><select name="slot_id" aria-label="New appointment time">{slots.filter(s=>s.service?.id===a.service?.id).map(s=><option value={s.id} key={s.id}>{new Intl.DateTimeFormat("en-BW",{dateStyle:"medium",timeStyle:"short"}).format(new Date(s.starts_at))}</option>)}</select><button className="button button--quiet">Reschedule</button></form>}<form action={cancelAppointment}><input type="hidden" name="appointment_id" value={a.id}/><button className="button button--quiet">Cancel</button></form></div>}</article>)}</div>
 {!items.length&&<div className="empty-state"><CalendarDays/><h2>No appointments yet</h2><p>Choose an available service and time that works for you.</p><Link href="/client/appointments/new">Find a time</Link></div>}</div>;
}

