import { updateCommunicationPreferences } from "@/app/client/actions";
import { getClientContext } from "@/lib/client-data";

type Props = { searchParams: Promise<{ saved?: string; error?: string }> };

export default async function PreferencesPage({ searchParams }: Props) {
  const [client, params] = await Promise.all([getClientContext(), searchParams]);
  const preferences = client.preferences;
  return <div className="portal-page form-page"><div className="portal-heading"><div><p className="welcome-line">Communication choices</p><h1>Preferences</h1><p>Choose how Tebelopele may contact you. Service-specific consent may still be required.</p></div></div>{params.saved && <div className="alert alert--success" role="status">Your communication choices were saved.</div>}{params.error && <div className="alert alert--error" role="alert">Your choices could not be saved. Check the form and try again.</div>}<form action={updateCommunicationPreferences} className="settings-form"><fieldset disabled={!client.configured}><legend>Language and preferred channel</legend><div className="field-grid"><label>Preferred language<select name="preferred_language" defaultValue={preferences.preferredLanguage}><option value="en">English</option><option value="tn">Setswana</option></select></label><label>Preferred channel<select name="preferred_channel" defaultValue={preferences.preferredChannel}><option value="in_app">In-app</option><option value="email">Email</option><option value="sms">SMS</option><option value="whatsapp">WhatsApp</option></select></label></div><legend>Channels you allow</legend><div className="choice-list"><label><input type="checkbox" name="allow_email" defaultChecked={preferences.allowEmail}/><span><strong>Email</strong><small>Service messages may be sent to your verified email.</small></span></label><label><input type="checkbox" name="allow_sms" defaultChecked={preferences.allowSms}/><span><strong>SMS</strong><small>Standard message charges may apply.</small></span></label><label><input type="checkbox" name="allow_whatsapp" defaultChecked={preferences.allowWhatsapp}/><span><strong>WhatsApp</strong><small>Private records still require an approved identity check.</small></span></label></div><div className="form-actions"><button className="button button--primary">Save preferences</button></div></fieldset></form></div>;
}
