"use client";
import Link from "next/link"; import {useState} from "react"; import {ArrowRight,BarChart3,Bot,CalendarDays,CheckCircle2,FileText,HeartHandshake,MapPin,MessageCircleMore,ShieldCheck,Users,Waypoints} from "lucide-react";
const journeys=[
  {id:"discover",label:"Find care",icon:MapPin,title:"Discover approved services",copy:"Explore service information, locations and practical preparation guidance without creating an account.",steps:["Browse the service directory","Compare published locations","Open approved health information"]},
  {id:"client",label:"Client portal",icon:CalendarDays,title:"Manage a personal care journey",copy:"See how a client handles profile details, consent, communication preferences, appointments and notifications.",steps:["Review consent choices","Book an available appointment","Receive reminders and updates"]},
  {id:"assistant",label:"AI & support",icon:Bot,title:"Ask, escalate and keep context",copy:"Try suggested questions, see grounded-source labels and follow an escalation into a human support queue.",steps:["Ask an approved FAQ","Request an eligible expert","Continue with the same transcript"]},
  {id:"operations",label:"Staff operations",icon:Users,title:"Operate with role-based access",copy:"Preview appointments, governed content, referral follow-up, reporting, audit history and integration health.",steps:["Claim skill-matched work","Record an auditable action","View only permitted reports"]},
];
export function DemoExperience(){const [active,setActive]=useState(journeys[0]);const Icon=active.icon;return <div className="demo-experience"><div className="demo-tabs" role="tablist" aria-label="Platform demo areas">{journeys.map(j=><button key={j.id} role="tab" aria-selected={active.id===j.id} onClick={()=>setActive(j)}><j.icon/>{j.label}</button>)}</div><section className="demo-stage"><div className="demo-stage__copy"><span className="demo-stage__icon"><Icon/></span><h2>{active.title}</h2><p>{active.copy}</p><ol>{active.steps.map((step,index)=><li key={step}><span>{index+1}</span>{step}<CheckCircle2/></li>)}</ol></div><div className="demo-preview" aria-label={`${active.label} interface preview`}><header><span>Tebelopele demonstration</span><small>No real records</small></header>{active.id==="discover"&&<><article><MapPin/><span><strong>Find a service near you</strong><small>Published locations and opening information</small></span><ArrowRight/></article><article><FileText/><span><strong>Approved health information</strong><small>Sources and review status remain visible</small></span><ArrowRight/></article></>}{active.id==="client"&&<><div className="demo-preview__status"><CalendarDays/><span><small>Next appointment</small><strong>Wellness consultation</strong><em>Demonstration record</em></span></div><article><ShieldCheck/><span><strong>Consent and preferences</strong><small>Change permitted choices at any time</small></span><ArrowRight/></article></>}{active.id==="assistant"&&<><div className="demo-chat"><p>How can counselling support me?</p><p>Tebelopele can help you explore approved support options. Would you like a human navigator?</p></div><article><HeartHandshake/><span><strong>Expert requested</strong><small>Matched by verified skill and availability</small></span><CheckCircle2/></article></>}{active.id==="operations"&&<><article><MessageCircleMore/><span><strong>Support queue</strong><small>Skill-matched cases and complete transcripts</small></span><strong>3</strong></article><article><Waypoints/><span><strong>Referral follow-up</strong><small>Status history and next action</small></span><strong>2</strong></article><article><BarChart3/><span><strong>Scoped reporting</strong><small>Counts trace back to authorized records</small></span><ArrowRight/></article></>}</div></section><div className="demo-next"><span><strong>Ready to explore the real workspace?</strong><small>Use a demonstration account or sign in with your own authorized profile.</small></span><Link className="button button--primary" href="/sign-in">Continue to sign in <ArrowRight/></Link></div></div>}
