import { recordConsentDecision } from "@/app/client/actions";
import { getConsentContext } from "@/lib/client-data";

type Props = { searchParams: Promise<{ saved?: string; error?: string }> };

export default async function ConsentPage({ searchParams }: Props) {
  const [context, params] = await Promise.all([getConsentContext(), searchParams]);
  return <div className="portal-page form-page"><div className="portal-heading"><div><p className="welcome-line">Your permissions</p><h1>Consent</h1><p>Review what you have agreed to and record a new decision when an active consent notice is available.</p></div></div>{params.saved && <div className="alert alert--success" role="status">Your consent decision was recorded with its policy version.</div>}{params.error && <div className="alert alert--error" role="alert">The consent decision could not be recorded.</div>}{!context.configured && <div className="preview-notice"><strong>Supabase required</strong><span>Consent versions and decisions are stored only when the database is connected.</span></div>}{context.configured && !context.versions.length && <div className="empty-state"><h2>No active consent notices</h2><p>Tebelopele-approved consent wording will appear here when published.</p></div>}<div className="consent-list">{context.versions.map((version) => { const decision = context.latest.get(version.id); return <article key={version.id}><div><span className="status-label">{decision ?? "No decision"}</span><h2>{version.title}</h2><p>{version.summary}</p><details><summary>Read full notice</summary><p>{version.full_text}</p><small>Version {version.version_number} · Effective {new Date(version.effective_at).toLocaleDateString("en-BW")}</small></details></div><form action={recordConsentDecision}><input type="hidden" name="consent_version_id" value={version.id}/>{decision === "accepted" ? <button className="button button--quiet" name="decision" value="withdrawn">Withdraw consent</button> : <><button className="button button--primary" name="decision" value="accepted">Accept</button><button className="button button--quiet" name="decision" value="declined">Decline</button></>}</form></article>; })}</div></div>;
}
